apiVersion: v1
kind: ConfigMap

metadata:
  name: microservices-config

data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: microservices_db
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_db

  EUREKA_SERVER: http://eureka-server:8761/eureka

  AUTH_SERVER: http://auth-server:9000

  ZIPKIN_SERVER: http://zipkin:9411/api/v2/spans

